name: deploy-pages

on:
  push:
    branches: [master]

jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to master
        uses: actions/checkout@v2
        with:
          ref: "master"

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Build the book
        run: |
          jupyter-book build .

      - name: Copy docs to tmp
        run: |
          mv ./_build/html /tmp/docs

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: test/_build/html
